// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eclrnxqfpctsdmkxhhht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbHJueHFmcGN0c2Rta3hoaGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTUzNzAsImV4cCI6MjA2MDI5MTM3MH0.tzCC7qEakPK_hVWjRVFVHyfut3x5N9p5JOUBR6bjU1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);